### ISSUE TITLE
Transitioning from fragments to executables

### ISSUE THREAD

**Issue by sadelbrid** [sadelbrid/SmartAlarm#10]
So far each module has existed and executed within it's own fragment. It is now time to move that functionality into executables (i.e. WeatherExec, RedditExec, etc.) The fragments will now only be used to add modules to the device's shared preferences. Then when the alarm triggers, those modules are loaded from local memory and executed via their respected executables.

Modules will be saved in shared preferences as strings. 
Example: A weather module where the user wants the weather description, currentTemp, not maxTemp, Celsius, and a querried latitude and longitude will be stored as "110C{lat},{lon}".
The WeatherExec then parses that info from the string.

NOTE: When storing modules that may contain duplicates (multiple subreddit modules), store under keys "REDDIT_PREFS_0", "REDDIT_PREFS_1", "REDDIT_PREFS_2" ... and pass the index to your constructor.

**Comment by sadelbrid** [comment]
Weather and Reddit modules complete.

**Comment by drewg2009** [comment]
nice work. either tomorrow or sunday i want to meet about a log error i am
getting on my end
